# Default to docker's mysql:
database_url: 'sqlite:///koe.db'

# Other database url:
#database_url: 'mysql://USER:PASSWORD@HOST:PORT/NAME'
#database_url: 'postgres://USER:PASSWORD@HOST:PORT/NAME'

language_code: 'en-nz'
timezone: 'UTC'
debug: True
allowed_hosts:
    - 'localhost'
    - '0.0.0.0'
    - '127.0.0.1'

site_url: 'http://127.0.0.1:8000/'
email_config: 'console'
csrf_trusted_origin:
    - '127.0.0.1'

session_cookie_secure: True

cache:
    backend: 'django_redis.cache.RedisCache'
    location: 'redis://localhost:6379/0'
    options:
        CLIENT_CLASS: 'django_redis.client.DefaultClient'
        COMPRESSOR: 'django_redis.compressors.zlib.ZlibCompressor'
        IGNORE_EXCEPTIONS: True
        PASSWORD: 'abc123'

environment_variables:
    WEBPACK_SERVER_PORT: 9876
